// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Codefusion.Jaskier.Web.Services.TrainingServiceAPI.Models
{
    public partial class InputParameters
    {
        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        public InputParameters() { }

        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        /// <param name="projectName">character</param>
        public InputParameters(string projectName = default(string))
        {
            this.ProjectName = projectName;
        }

        /// <summary>
        /// Gets or sets character
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

    }
}
