// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Codefusion.Jaskier.Web.Services.TrainingServiceAPI.Models
{
    public partial class StartBatchExecutionResponse
    {
        /// <summary>
        /// Initializes a new instance of the StartBatchExecutionResponse
        /// class.
        /// </summary>
        public StartBatchExecutionResponse() { }

        /// <summary>
        /// Initializes a new instance of the StartBatchExecutionResponse
        /// class.
        /// </summary>
        /// <param name="batchExecutionId">Id of the asynchronous
        /// execution.</param>
        public StartBatchExecutionResponse(string batchExecutionId = default(string))
        {
            this.BatchExecutionId = batchExecutionId;
        }

        /// <summary>
        /// Gets or sets id of the asynchronous execution.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "batchExecutionId")]
        public string BatchExecutionId { get; set; }

    }
}
